---
environments:
  prod:
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
      - environments/prod/kube-prometheus-stack.values.yaml
      - environments/prod/loki.values.yaml
      - environments/prod/alloy.values.yaml
      - environments/{{ .Environment.Name }}/app-probes.values.yaml
  ci:
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
      - environments/prod/kube-prometheus-stack.values.yaml
      - environments/prod/loki.values.yaml
      - environments/prod/alloy.values.yaml
      - environments/{{ .Environment.Name }}/app-probes.values.yaml

helmfiles:
  - path: releases/grafana-admin-secret.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
  - path: releases/http-redirect-middleware.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
  - path: releases/kube-prometheus-stack.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
      - environments/prod/kube-prometheus-stack.values.yaml
  - path: releases/blackbox-exporter.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
  - path: releases/app-probes.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
      - environments/{{ .Environment.Name }}/app-probes.values.yaml
  - path: releases/traefik-servicemonitor.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
  - path: releases/recording-rules.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
  - path: releases/alert-rules.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
  - path: releases/dashboards-overview.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
  - path: releases/dashboards-n8n-runtime.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
  - path: releases/dashboards-public-endpoints.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
  - path: releases/loki.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
      - environments/prod/loki.values.yaml
  - path: releases/alloy.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
      - environments/prod/alloy.values.yaml
  - path: releases/networkpolicy.yaml
    values:
      - environments/{{ .Environment.Name }}/meta.values.yaml
