---
auth:
  enablePostgresUser: true
  username: ''
  database: ''

primary:
  initdb:
    scriptsSecret: postgres-initdb-scripts
  persistence:
    enabled: true
    storageClass: local-path
    size: 20Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
