auth:
  postgresPassword: ENC[AES256_GCM,data:CBlm8DMWsbLO98Y/R8KGkH0cRCWIhrEwixNdhOTp8n6sOuc71uJSXpVYG19GrUKS,iv:7xqUg9lnv/HRdRsSFNfdqWPQawB1e024IQJ1zAekJlQ=,tag:t0Wc9RAJ80989uPTWEpSpA==,type:str]
db_users:
  n8n_password: ENC[AES256_GCM,data:FcE9xPqcg1BqgmR5jvS5ooIiE8i486LfBPtWRBb7ufA=,iv:aIzqnUWYGICHqz7Z/bitnRQOEYF1k2vOPBAK/XAcJM0=,tag:MIyepWK2i2238jAsXZ9+zg==,type:str]
  wikijs_password: ENC[AES256_GCM,data:2zwRLwlWmxM2VU/31IF7MFF9a2+3XrY9ouAUxGJao3I=,iv:QF6cLKTIFVtG+JjXANleGmdQuM83WYFCCqGCeT7qvfc=,tag:pga/9ezsq5TGX0MU+VZ7Jg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1l4t3wd0cnxzqskhgttme07pg4lfsd8twsh2qppcdjqy3shtahq8salfrxu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WlJialVkdUFnb2lmczU1
        VUFBcUczWlllZEVBVjhmWUYwUVlSeTJWbEZBClc3WER6M1hDRXFHNktsaDhiTnJy
        TTc1SDE4b3ZvU0l0QU84ZFFTd0VDVzAKLS0tIFNmdWNDbEdPQjFPc0NPSUFsOXpM
        MzZnWjZaQTZSSngxby85VTNMai9LWEUKUmJK05+qOEHUuvWChJjPe79u6QNRReg2
        eH+4eNyYE4AOswOkaGguXSCJAPvPsCHQMr67Lcdrkot0sDdtAxnbEw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2026-04-23T17:00:38Z'
  mac: ENC[AES256_GCM,data:BSPL2CI+ySehlD1gIKWjSh7L3eW4dBWvyMa3kFwvQQIOlub8PTDBAxSy+K0bQMDdajDRkHrfVqguxRQuDheBGBkEy+P4uaWjPK9KiNpHMA9OPElC0KTlhKNf0C2y2MTitsid53McMBDNTHqXkdaXH3w1y9Uqa4twWH1n7FCVbOo=,iv:wSPVihIijQZnfHEpzZkozb0oJwlJrhGp80kArEn1a28=,tag:SE4+5z84cWLoNe9bLPmwUA==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.9.4
