---
environments:
  prod:
    values:
      - environments/prod/meta.values.yaml
      - environments/prod/app.values.yaml

helmfiles:
  - path: releases/networkpolicy.yaml
    values:
      - environments/prod/meta.values.yaml
  - path: releases/http-redirect-middleware.yaml
    values:
      - environments/prod/meta.values.yaml
  - path: releases/db-secret.yaml
    values:
      - environments/prod/meta.values.yaml
      - environments/prod/app.values.yaml
  - path: releases/wikijs.yaml
    values:
      - environments/prod/meta.values.yaml
      - environments/prod/app.values.yaml
