---
environments:
  prod:
    values:
      - environments/prod/cert-manager.values.yaml
      - environments/prod/cluster-issuer.values.yaml

helmfiles:
  - path: releases/namespaces.yaml
    values:
      - environments/prod/namespaces.values.yaml
  - path: releases/cert-manager.yaml
    values:
      - environments/prod/cert-manager.values.yaml
  - path: releases/cluster-issuer.yaml
    values:
      - environments/prod/cluster-issuer.values.yaml
