---
helmDefaults:
  skipDeps: true

releases:
  - name: n8n
    namespace: {{ .Values.namespace | quote }}
    createNamespace: false
    chart: ../chart
    wait: true
    values:
      - ../environments/prod/app.values.yaml
      - secrets:
          dbPassword: {{ "{{ .Values.db_users.n8n_password }}" | quote }}
          wikiDbPassword: {{ "{{ .Values.db_users.wikijs_password }}" | quote }}
          redisPassword: {{ "{{ .Values.redis_auth.password }}" | quote }}
    secrets:
      - ../environments/prod/secrets.values.enc.yaml
      - ../../postgres/environments/prod/secrets.values.enc.yaml
      - ../../redis/environments/prod/secrets.values.enc.yaml
