---
helmDefaults:
  skipDeps: true

releases:
  - name: wiki-db-secret
    namespace: {{ .Values.namespace | quote }}
    createNamespace: false
    chart: ../../../vendor_charts/raw
    wait: true
    values:
      - templates:
          - |
            apiVersion: v1
            kind: Secret
            metadata:
              name: {{ .Values.externalPostgresql.existingSecret | quote }}
            type: Opaque
            stringData:
              {{ .Values.externalPostgresql.existingSecretKey | quote }}: {{ "{{ .Values.db_users.wikijs_password }}" | quote }}
    secrets:
      - ../../postgres/environments/prod/secrets.values.enc.yaml
