---
helmDefaults:
  skipDeps: true

releases:
  - name: postgres
    namespace: {{ .Values.namespace | quote }}
    createNamespace: false
    chart: ../../../vendor_charts/postgresql
    wait: true
    values:
      {{- if eq .Environment.Name "prod" }}
      - ../environments/prod/secrets.values.enc.yaml
      {{- else }}
      - ../environments/ci/secrets.values.yaml
      {{- end }}
      - ../environments/prod/app.values.yaml
