---
helmDefaults:
  skipDeps: true

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: ../../vendor_charts/cert-manager
    values:
      - ../environments/prod/cert-manager.values.yaml
