---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ollama.name" . }}-cm
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
data:
  OLLAMA_HOST: {{ required "ollama.env.OLLAMA_HOST is required" .Values.ollama.env.OLLAMA_HOST | quote }}
  OLLAMA_KEEP_ALIVE: {{ required "ollama.env.OLLAMA_KEEP_ALIVE is required" .Values.ollama.env.OLLAMA_KEEP_ALIVE | quote }}
