---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ollama.name" . }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  replicas: {{ .Values.ollama.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "ollama.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ollama
  template:
    metadata:
      labels:
        {{- include "ollama.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ollama
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: ollama
          image: {{ include "ollama.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "ollama.name" . }}-cm
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: models-storage
              mountPath: {{ .Values.persistence.mountPath | quote }}
          {{- end }}
          {{- if .Values.ollama.probes.enabled }}
          startupProbe:
            {{- toYaml .Values.ollama.probes.startup | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.ollama.probes.readiness | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.ollama.probes.liveness | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.ollama.resources | nindent 12 }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: models-storage
          persistentVolumeClaim:
            claimName: {{ include "ollama.pvcName" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
