{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ollama.name" . }}-pvc
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end -}}
