redis_auth:
    password: ENC[AES256_GCM,data:A972GXTxdkhCXr1Sgr6K9ljXEAlXaFZ6KIHkx2Refn/unOzk1c4lqd6BQIIfHeyt,iv:+LMtbTnQ3OKCQU4KWAhiRZLB+70rR2RCtcbGO1WdP2E=,tag:FddsgBCK+beekDzf7+CLkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l4t3wd0cnxzqskhgttme07pg4lfsd8twsh2qppcdjqy3shtahq8salfrxu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ2FtdzBpN1laZ1d6Um9o
            NkV1S0xTaUtKenFEZUo5ZG1GSlc1QU9IRUdRCnNUVURUSGpROHdTVldKdG5OWkxp
            RWR0ejdtWjBrSjI3SkVscHVVYVJFc1kKLS0tIERkYVZ2dzFLcWlqZ21FY0w0N2dv
            c2M2N0Mvek1vRVJITHR4ejVDSXBlemsKkzgwyct4MPGd3cTtkXQQOqM+VOz26WVd
            oljV1H0R5lCaPmS9BF97jtIf4qspIiscu9Ta3gLctxuh0Dxx/KytYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T16:35:07Z"
    mac: ENC[AES256_GCM,data:s6PyBMiEoImkJJXvc3+nPm7b/U6555DMy5bcYg+ET304jHqzyw5MhDgnbZuLtWHWLuQKKnLbGDOWoNJUtptHpPStuCiiV7GuyjNKcRsXhSuN3ZkBuumEQjc08BtqSMZMWn9EMgyGAnl7HNpDqByiC7+KOVUxTWwWeApYPp9J8gQ=,iv:ZmMu9j0/Ti8A/GR0HgVdS+cdjQiYkS+gIxyMQgBbRqY=,tag:CmRqCWu/x0y1q81OkoXZQQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
