---
helmDefaults:
  skipDeps: true

releases:
  - name: redis-auth-secret
    namespace: {{ .Values.namespace | quote }}
    createNamespace: false
    chart: ../../../vendor_charts/raw
    wait: true
    secrets:
      - ../environments/prod/secrets.values.enc.yaml
    values:
      - ../environments/prod/app.values.yaml
      - templates:
          - |
            apiVersion: v1
            kind: Secret
            metadata:
              name: {{ .Values.redis_auth_secret_name | quote }}
            type: Opaque
            stringData:
              {{ .Values.redis_auth_secret_key | quote }}: {{ "{{ .Values.redis_auth.password }}" | quote }}
