---
base_supported_os_families:
  - Debian
  - RedHat

base_packages_common:
  - ca-certificates
  - curl
  - tzdata

base_packages_debian:
  - gnupg

base_packages_redhat:
  - gnupg2

base_directories:
  - /opt/ai-agent

base_manage_timezone: false

base_timezone: UTC
