---
- name: Apply ollama stack changes
  community.docker.docker_compose_v2:
    project_src: '{{ ollama_project_dir }}'
    state: present
    wait: "{{ ollama_compose_wait | bool }}"
    wait_timeout: "{{ ollama_compose_wait_timeout | int }}"
    timeout: "{{ ollama_compose_cli_timeout | int }}"
  async: "{{ ollama_compose_apply_async_timeout | int }}"
  poll: "{{ ollama_compose_apply_poll | int }}"
  listen: Apply ollama stack changes
  when: not (ollama_deploy_executed | default(false) | bool)
  tags: [ollama, ollama_handlers]
