---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.name" . }}-worker
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "n8n.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: n8n-worker
          image: {{ include "n8n.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["n8n"]
          args: ["worker"]
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: NODE_ENV
              value: production
            - name: N8N_DISABLE_UI
              value: "true"
            - name: QUEUE_HEALTH_CHECK_ACTIVE
              value: "true"
          envFrom:
            - configMapRef:
                name: {{ include "n8n.name" . }}-cm
            - secretRef:
                name: {{ include "n8n.name" . }}-secret
          {{- with .Values.worker.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
