---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.name" . }}-secret
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
{{- $dbPassword := tpl (toString .Values.secrets.dbPassword) . }}
{{- $wikiDbPassword := tpl (toString .Values.secrets.wikiDbPassword) . }}
{{- $redisPassword := tpl (toString .Values.secrets.redisPassword) . }}
{{- $encryptionKey := tpl (toString .Values.secrets.encryptionKey) . }}
stringData:
  DB_POSTGRESDB_PASSWORD: {{ $dbPassword | quote }}
  WIKI_POSTGRESDB_PASSWORD: {{ $wikiDbPassword | quote }}
  QUEUE_BULL_REDIS_PASSWORD: {{ $redisPassword | quote }}
  N8N_ENCRYPTION_KEY: {{ $encryptionKey | quote }}
