---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.name" . }}-web-svc
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type | quote }}
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
