---
- name: Import validation tasks
  ansible.builtin.import_tasks: validate.yml
  tags: [docker, validation]

- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
  tags: [docker, packages]

- name: Import service tasks
  ansible.builtin.import_tasks: service.yml
  tags: [docker, service]

- name: Import verification tasks
  ansible.builtin.import_tasks: verify.yml
  when: docker_engine_validate_installation | bool
  tags: [docker, verify]
