---
- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  when: docker_engine_manage_user_group | bool

- name: Ensure Docker service state and enablement
  ansible.builtin.service:
    name: docker
    enabled: "{{ docker_engine_service_enabled }}"
    state: "{{ docker_engine_service_state }}"

- name: Add deployment user to docker group
  ansible.builtin.user:
    name: '{{ docker_engine_group_user }}'
    groups: docker
    append: true
  when:
    - docker_engine_manage_user_group | bool
    - docker_engine_group_user | trim | length > 0
