grafana_admin:
    password: ENC[AES256_GCM,data:GB6XpMs=,iv:iwkaknHLGBpnfXnbIN20q0291nJj68mGReOSnreOeNA=,tag:1I5HItb/n8z2f3yrdFfieg==,type:str]
alertmanager:
    smtp:
        auth_password: ENC[AES256_GCM,data:1IarcqK1YGK2RdqGpSLrAA==,iv:kySJKeQdRFIMX3YYuBP7M/OXlTS+a8W0e0G/B+MTCzo=,tag:RvIXkS6O5/ws3N5tdtbJ4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l4t3wd0cnxzqskhgttme07pg4lfsd8twsh2qppcdjqy3shtahq8salfrxu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYmFMSDVsTVoxWGhkWEVz
            S01YVjRtRWdmUWhIOTVsZjh6Z2NtcGFNc1NnCkZnWFBSZnh6VGE4dWFGbkRBVGRi
            elNBU09hdU9za2JzNFVJNWl3ZzlYUFUKLS0tIDRoeUFmMWQ3dDNqZWI4WWZGR1J4
            VVdvM2pWYXFDbTZ5UDJNcHUyeFB3eUkK0sgplibOT+/izH6JUZRYGd5P1T3iVSca
            qGJ1lcJCBtDCvPtS1Gup+pPDTfK75c2YtgbL2W8awMM+ZThH6KyIHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T05:59:54Z"
    mac: ENC[AES256_GCM,data:eRz695D8zb7ffBgMO7nt44W7Qft16/RJsGzoMLdardcrKv4OrAcFpOuwWULpTdFv3nik6QJ/bm/r9FnuSukv1Xbzhii1Iwa8FulpHhB/OLCezjaxRlvBDT70gHhE4NkyWbEraOsc0RdlPGB5LwQEk/XOd5pqyDV2cRJSM3p9OFM=,iv:arSuzxIyhUgMDAT/4FzR1/A/k/XsauzJIPy3mS1FWns=,tag:8XklpKOPGfxoQIQrd+I2Fw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
