secrets:
    encryptionKey: ENC[AES256_GCM,data:Crb9LA4FqQr8XWoEgKIgfABMKXj0ebWksD4hZvM2SqLI31ZXQAwSRMCz/G67Yt3P49w7DdEDMIQFp4pwF5r/IQ==,iv:i61d3vAYdmj2TL55JMhU4BAdZK3GfSqoxlNX0h1ENVE=,tag:gDOTa5TAc+Mkp8unueWlCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l4t3wd0cnxzqskhgttme07pg4lfsd8twsh2qppcdjqy3shtahq8salfrxu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRXhuTTVKUXYzQkJsNzFu
            ak9mSVB4TjhGVWJuSWpPdjNUM0JlVmlVSlJzClI4OVpiVS9ldndtdHY0eXFSNmh0
            WXZlK0xtRjNoRjJkcStnUXloNExmOFUKLS0tIDZjN1JrU1d6SEpuU3NMOUVFSXQ5
            a0gzSVJXNVJpakI2UXk5Q245VzM3U1kKMDT9xv4/jw91hmREfBzyazyimUfdd+cf
            Mtwt6yL/umRuJypSk6KNLeVv+QgzMhFbcs/j60Yh2T9DR+SfmpMSIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T09:26:12Z"
    mac: ENC[AES256_GCM,data:IVN6bEF/b3PJsBuA191B1NaiR2CRUGElXNjMvVT1cJWmIuOhQhLNsWps6a2eaHVVDnmdXrDYCW4xW+ICVGZiYqirhPI9Fyf18d50366ZWdiA+7F43cp5LwKi06eV/Wcv19qQ96mx4wFsBLXV7a3JkRRTIMHRYKVIr+tiiK5SRq8=,iv:kwMa8MpPXAoKjrnbUj713pf8idfa0pdYT32nrxUd4tQ=,tag:+XyM0EIKJj5nqaJyxfUyjA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
