---
postgres_backup_cron_enabled: true

firewall_ssh_sources:
  - "{{ hostvars['wiki'].private_ip }}/32"

firewall_rules:
  - port: 5432
    proto: tcp
    source: "{{ hostvars['n8n'].private_ip }}/32"
  - port: 5432
    proto: tcp
    source: "{{ hostvars['wiki'].private_ip }}/32"

postgres_hba_rules:
  - type: host
    database: all
    user: all
    address: 127.0.0.1/32
    method: '{{ postgres_password_encryption }}'
  - type: host
    database: all
    user: all
    address: ::1/128
    method: '{{ postgres_password_encryption }}'
  - type: host
    database: '{{ postgres_n8n_db }}'
    user: '{{ postgres_n8n_user }}'
    address: "{{ hostvars['n8n'].private_ip }}/32"
    method: '{{ postgres_password_encryption }}'
  - type: host
    database: '{{ postgres_wiki_db }}'
    user: '{{ postgres_wiki_user }}'
    address: "{{ hostvars['wiki'].private_ip }}/32"
    method: '{{ postgres_password_encryption }}'
