---
helmDefaults:
  skipDeps: true

releases:
  - name: grafana-admin-secret
    namespace: {{ .Values.namespace | quote }}
    createNamespace: false
    chart: ../../vendor_charts/raw
    wait: true
    secrets:
      {{- if eq .Environment.Name "prod" }}
      - ../environments/prod/secrets.values.enc.yaml
      {{- end }}
    values:
      {{- if eq .Environment.Name "ci" }}
      - ../environments/ci/validation.values.yaml
      {{- end }}
      - templates:
          - |
            apiVersion: v1
            kind: Secret
            metadata:
              name: observability-grafana-admin
            type: Opaque
            stringData:
              admin-user: admin
              admin-password: {{ "{{ .Values.grafana_admin.password }}" | quote }}
